version: '3.7'
volumes:
  grafana_data: {}
  prometheus_data: {}
services:
  prometheus:
    image: prom/prometheus:v2.12.0
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
  grafana:
    image: grafana/grafana:5.4.5
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/datasources
      - ./grafana/dashboards:/etc/grafana/dashboards
    depends_on:
      - prometheus
  cadvisor:
    image: google/cadvisor:v0.33.0
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  conversation-app:
    build:
      context: './conversation-app'
      dockerfile: 'Dockerfile-prod'
    image: conversation-app:0.1.0
    ports:
      - 5050:80
